services:
  rbac-db:
    image: postgres:16.1
    container_name: postgres-rbac-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rbac
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - rbacnet

  backend:
    build:
      context: ../backend_access
      dockerfile: Dockerfile
    container_name: rbac-backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - FRONTEND_URL=${FRONTEND_URL}
      - YANDEX_ACCESS_KEY_ID=${YANDEX_ACCESS_KEY_ID}
      - YANDEX_SECRET_ACCESS_KEY=${YANDEX_SECRET_ACCESS_KEY}
      - YANDEX_BUCKET_NAME=${YANDEX_BUCKET_NAME}
      - YANDEX_REGION=${YANDEX_REGION}
    depends_on:
      rbac-db:
        condition: service_healthy
    restart: always
    networks:
      - rbacnet

  rbac:
    build: .
    container_name: rbac
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_S3_ENDPOINT=${NEXT_PUBLIC_S3_ENDPOINT}
      - NEXT_PUBLIC_S3_BUCKET=${NEXT_PUBLIC_S3_BUCKET}
      - NEXT_PUBLIC_S3_REGION=${NEXT_PUBLIC_S3_REGION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    depends_on: # Добавлена зависимость от backend
      - backend
    networks:
      - rbacnet

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-rbac
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf:/etc/nginx/conf.d
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
      # - ./dhparam.pem:/etc/nginx/dhparam.pem
    depends_on:
      - rbac
      - backend
    ports:
      - "80:80"
      # - "443:443"
    networks:
      - rbacnet

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   depends_on:
  #     - nginx
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email pavlikdemin@ya.ru --agree-tos --no-eff-email -d rosatomaccess.ru -d www.rosatomaccess.ru --keep-until-expiring --non-interactive

volumes:
  db_data:

networks:
  rbac-net:
    name: rbacnet
    driver: bridge