import React from 'react';

interface DataType {
  key: React.Key;
  name: string;
  rang: string;
  subdivision: string;
  address: string;
}

export const usersData: DataType[] = [
  {
    key: 1,
    name: 'Иванов Алексей Сергеевич',
    rang: 'Инженер',
    subdivision: 'Отдел разработки',
    address: 'ivanov.as@mail.ru',
  },
  {
    key: 2,
    name: 'Петрова Елена Владимировна',
    rang: 'Менеджер проектов',
    subdivision: 'Управление проектами',
    address: 'petrova.ev@mail.ru',
  },
  {
    key: 3,
    name: 'Сидоров Дмитрий Николаевич',
    rang: 'Аналитик данных',
    subdivision: 'Аналитический отдел',
    address: 'sidorov.dn@mail.ru',
  },
  {
    key: 4,
    name: 'Кузнецова Ольга Игоревна',
    rang: 'Бухгалтер',
    subdivision: 'Финансовый отдел',
    address: 'kuznetsova.oi@mail.ru',
  },
  {
    key: 5,
    name: 'Смирнов Артем Васильевич',
    rang: 'Разработчик',
    subdivision: 'IT-отдел',
    address: 'smirnov.av@mail.ru',
  },
  {
    key: 6,
    name: 'Федорова Анна Павловна',
    rang: 'HR-специалист',
    subdivision: 'Отдел кадров',
    address: 'fedorova.ap@mail.ru',
  },
  {
    key: 7,
    name: 'Николаев Максим Андреевич',
    rang: 'Системный администратор',
    subdivision: 'IT-отдел',
    address: 'nikolaev.ma@mail.ru',
  },
  {
    key: 8,
    name: 'Волкова Ирина Сергеевна',
    rang: 'Маркетолог',
    subdivision: 'Отдел маркетинга',
    address: 'volkova.is@mail.ru',
  },
  {
    key: 9,
    name: 'Белов Александр Дмитриевич',
    rang: 'Тестировщик',
    subdivision: 'Отдел контроля качества',
    address: 'belov.ad@mail.ru',
  },
  {
    key: 10,
    name: 'Григорьева Татьяна Олеговна',
    rang: 'Дизайнер',
    subdivision: 'Отдел дизайна',
    address: 'grigoreva.to@mail.ru',
  },
  {
    key: 11,
    name: 'Дмитриев Павел Викторович',
    rang: 'Инженер-программист',
    subdivision: 'Отдел разработки',
    address: 'dmitriev.pv@mail.ru',
  },
  {
    key: 12,
    name: 'Орлова Мария Ивановна',
    rang: 'Копирайтер',
    subdivision: 'Отдел маркетинга',
    address: 'orlova.mi@mail.ru',
  },
  {
    key: 13,
    name: 'Киселев Андрей Петрович',
    rang: 'Менеджер по продажам',
    subdivision: 'Коммерческий отдел',
    address: 'kiselev.ap@mail.ru',
  },
  {
    key: 14,
    name: 'Антонова Екатерина Алексеевна',
    rang: 'Юрист',
    subdivision: 'Юридический отдел',
    address: 'antonova.ea@mail.ru',
  },
  {
    key: 15,
    name: 'Тарасов Иван Владимирович',
    rang: 'Продукт-менеджер',
    subdivision: 'Управление продуктами',
    address: 'tarasov.iv@mail.ru',
  },
  {
    key: 16,
    name: 'Соколова Наталья Дмитриевна',
    rang: 'Финансовый аналитик',
    subdivision: 'Финансовый отдел',
    address: 'sokolova.nd@mail.ru',
  },
  {
    key: 17,
    name: 'Лебедев Сергей Александрович',
    rang: 'Архитектор ПО',
    subdivision: 'Отдел разработки',
    address: 'lebedev.sa@mail.ru',
  },
  {
    key: 18,
    name: 'Морозова Виктория Сергеевна',
    rang: 'Специалист по закупкам',
    subdivision: 'Отдел снабжения',
    address: 'morozova.vs@mail.ru',
  },
  {
    key: 19,
    name: 'Ковалев Денис Олегович',
    rang: 'DevOps-инженер',
    subdivision: 'IT-отдел',
    address: 'kovalev.do@mail.ru',
  },
  {
    key: 20,
    name: 'Зайцева Алина Михайловна',
    rang: 'Контент-менеджер',
    subdivision: 'Отдел маркетинга',
    address: 'zaitseva.am@mail.ru',
  },
  {
    key: 21,
    name: 'Гусев Роман Игоревич',
    rang: 'Сетевой инженер',
    subdivision: 'IT-отдел',
    address: 'gusev.ri@mail.ru',
  },
  {
    key: 22,
    name: 'Титова Ольга Васильевна',
    rang: 'Логист',
    subdivision: 'Отдел логистики',
    address: 'titova.ov@mail.ru',
  },
  {
    key: 23,
    name: 'Фомин Алексей Николаевич',
    rang: 'Руководитель отдела',
    subdivision: 'Отдел разработки',
    address: 'fomin.an@mail.ru',
  },
  {
    key: 24,
    name: 'Данилова Юлия Андреевна',
    rang: 'Специалист по кадрам',
    subdivision: 'Отдел кадров',
    address: 'danilova.ya@mail.ru',
  },
  {
    key: 25,
    name: 'Комаров Владислав Сергеевич',
    rang: 'Frontend-разработчик',
    subdivision: 'Отдел разработки',
    address: 'komarov.vs@mail.ru',
  },
  {
    key: 26,
    name: 'Егорова Анастасия Павловна',
    rang: 'Бизнес-аналитик',
    subdivision: 'Аналитический отдел',
    address: 'egorova.ap@mail.ru',
  },
  {
    key: 27,
    name: 'Борисов Илья Денисович',
    rang: 'Backend-разработчик',
    subdivision: 'Отдел разработки',
    address: 'borisov.id@mail.ru',
  },
  {
    key: 28,
    name: 'Михайлова Елена Викторовна',
    rang: 'Менеджер по работе с клиентами',
    subdivision: 'Отдел продаж',
    address: 'mikhailova.ev@mail.ru',
  },
  {
    key: 29,
    name: 'Тихонов Артем Сергеевич',
    rang: 'Технический писатель',
    subdivision: 'Отдел документации',
    address: 'tikhonov.as@mail.ru',
  },
  {
    key: 30,
    name: 'Ларина Татьяна Игоревна',
    rang: 'PR-менеджер',
    subdivision: 'Отдел маркетинга',
    address: 'larina.ti@mail.ru',
  },
  {
    key: 31,
    name: 'Семенов Денис Владимирович',
    rang: 'Инженер по качеству',
    subdivision: 'Отдел контроля качества',
    address: 'semenov.dv@mail.ru',
  },
  {
    key: 32,
    name: 'Герасимова Оксана Анатольевна',
    rang: 'Офис-менеджер',
    subdivision: 'Административный отдел',
    address: 'gerasimova.oa@mail.ru',
  },
  {
    key: 33,
    name: 'Кудрявцев Андрей Михайлович',
    rang: 'Системный аналитик',
    subdivision: 'Аналитический отдел',
    address: 'kudryavtsev.am@mail.ru',
  },
  {
    key: 34,
    name: 'Романова Светлана Васильевна',
    rang: 'Секретарь',
    subdivision: 'Административный отдел',
    address: 'romanova.sv@mail.ru',
  },
  {
    key: 35,
    name: 'Жуков Владимир Александрович',
    rang: 'Руководитель проекта',
    subdivision: 'Управление проектами',
    address: 'zhukov.va@mail.ru',
  },
  {
    key: 36,
    name: 'Савельева Ирина Дмитриевна',
    rang: 'Экономист',
    subdivision: 'Финансовый отдел',
    address: 'savelieva.id@mail.ru',
  },
  {
    key: 37,
    name: 'Мельников Павел Олегович',
    rang: 'Android-разработчик',
    subdivision: 'Мобильная разработка',
    address: 'melnikov.po@mail.ru',
  },
  {
    key: 38,
    name: 'Горбачева Анна Сергеевна',
    rang: 'Специалист по обучению',
    subdivision: 'Отдел обучения',
    address: 'gorbacheva.as@mail.ru',
  },
  {
    key: 39,
    name: 'Крылов Дмитрий Игоревич',
    rang: 'IOS-разработчик',
    subdivision: 'Мобильная разработка',
    address: 'krylov.di@mail.ru',
  },
  {
    key: 40,
    name: 'Максимова Виктория Андреевна',
    rang: 'Арт-директор',
    subdivision: 'Отдел дизайна',
    address: 'maksimova.va@mail.ru',
  },
  {
    key: 41,
    name: 'Филиппов Артем Николаевич',
    rang: 'Специалист по безопасности',
    subdivision: 'Отдел информационной безопасности',
    address: 'filippov.an@mail.ru',
  },
  {
    key: 42,
    name: 'Александрова Елена Владимировна',
    rang: 'Менеджер по рекламе',
    subdivision: 'Отдел маркетинга',
    address: 'aleksandrova.ev@mail.ru',
  },
  {
    key: 43,
    name: 'Степанов Игорь Сергеевич',
    rang: 'Инженер-электроник',
    subdivision: 'Отдел разработки',
    address: 'stepanov.is@mail.ru',
  },
  {
    key: 44,
    name: 'Козлова Марина Алексеевна',
    rang: 'Ассистент',
    subdivision: 'Административный отдел',
    address: 'kozlova.ma@mail.ru',
  },
  {
    key: 45,
    name: 'Ильин Антон Дмитриевич',
    rang: 'Руководитель отдела продаж',
    subdivision: 'Отдел продаж',
    address: 'ilin.ad@mail.ru',
  },
  {
    key: 46,
    name: 'Новикова Татьяна Сергеевна',
    rang: 'Бухгалтер-кассир',
    subdivision: 'Финансовый отдел',
    address: 'novikova.ts@mail.ru',
  },
  {
    key: 47,
    name: 'Сорокин Михаил Викторович',
    rang: 'Инженер-тестировщик',
    subdivision: 'Отдел контроля качества',
    address: 'sorokin.mv@mail.ru',
  },
  {
    key: 48,
    name: 'Власова Анастасия Игоревна',
    rang: 'Специалист по кадровому учету',
    subdivision: 'Отдел кадров',
    address: 'vlasova.ai@mail.ru',
  },
  {
    key: 49,
    name: 'Павлов Денис Андреевич',
    rang: 'Веб-дизайнер',
    subdivision: 'Отдел дизайна',
    address: 'pavlov.da@mail.ru',
  },
  {
    key: 50,
    name: 'Беляева Ольга Николаевна',
    rang: 'Менеджер по персоналу',
    subdivision: 'Отдел кадров',
    address: 'belyaeva.on@mail.ru',
  },
  {
    key: 51,
    name: 'Громов Алексей Владимирович',
    rang: 'Специалист по технической поддержке',
    subdivision: 'IT-отдел',
    address: 'gromov.av@mail.ru',
  },
  {
    key: 52,
    name: 'Карпова Юлия Александровна',
    rang: 'Менеджер по закупкам',
    subdivision: 'Отдел снабжения',
    address: 'karpova.ya@mail.ru',
  },
  {
    key: 53,
    name: 'Орлов Артем Денисович',
    rang: 'Специалист по внедрению',
    subdivision: 'Отдел внедрения',
    address: 'orlov.ad@mail.ru',
  },
  {
    key: 54,
    name: 'Медведева Екатерина Олеговна',
    rang: 'Специалист по документообороту',
    subdivision: 'Административный отдел',
    address: 'medvedeva.eo@mail.ru',
  },
  {
    key: 55,
    name: 'Кузьмин Сергей Викторович',
    rang: 'Инженер-конструктор',
    subdivision: 'Конструкторский отдел',
    address: 'kuzmin.sv@mail.ru',
  },
  {
    key: 56,
    name: 'Андреева Надежда Петровна',
    rang: 'Специалист по делопроизводству',
    subdivision: 'Административный отдел',
    address: 'andreeva.np@mail.ru',
  },
  {
    key: 57,
    name: 'Трофимов Виталий Сергеевич',
    rang: 'Специалист по тендерам',
    subdivision: 'Коммерческий отдел',
    address: 'trofimov.vs@mail.ru',
  },
  {
    key: 58,
    name: 'Симонова Алина Игоревна',
    rang: 'Менеджер по маркетингу',
    subdivision: 'Отдел маркетинга',
    address: 'simonova.ai@mail.ru',
  },
  {
    key: 59,
    name: 'Федотов Иван Алексеевич',
    rang: 'Специалист по CRM',
    subdivision: 'Отдел продаж',
    address: 'fedotov.ia@mail.ru',
  },
  {
    key: 60,
    name: 'Макарова Вероника Сергеевна',
    rang: 'Специалист по кадровой политике',
    subdivision: 'Отдел кадров',
    address: 'makarova.vs@mail.ru',
  },
  {
    key: 61,
    name: 'Давыдов Александр Николаевич',
    rang: 'Руководитель IT-отдела',
    subdivision: 'IT-отдел',
    address: 'davydov.an@mail.ru',
  },
  {
    key: 62,
    name: 'Ефимова Дарья Андреевна',
    rang: 'Специалист по внутренним коммуникациям',
    subdivision: 'HR-отдел',
    address: 'efimova.da@mail.ru',
  },
  {
    key: 63,
    name: 'Щербаков Денис Владимирович',
    rang: 'Специалист по закупкам IT',
    subdivision: 'Отдел снабжения',
    address: 'scherbakov.dv@mail.ru',
  },
  {
    key: 64,
    name: 'Калинина Анна Викторовна',
    rang: 'Финансовый менеджер',
    subdivision: 'Финансовый отдел',
    address: 'kalinina.av@mail.ru',
  },
  {
    key: 65,
    name: 'Гаврилов Максим Игоревич',
    rang: 'Специалист по информационным системам',
    subdivision: 'IT-отдел',
    address: 'gavrilov.mi@mail.ru',
  },
  {
    key: 66,
    name: 'Родионова Елена Сергеевна',
    rang: 'Специалист по обучению персонала',
    subdivision: 'Отдел обучения',
    address: 'rodionova.es@mail.ru',
  },
  {
    key: 67,
    name: 'Логинов Артем Владимирович',
    rang: 'Специалист по базам данных',
    subdivision: 'IT-отдел',
    address: 'loginov.av@mail.ru',
  },
  {
    key: 68,
    name: 'Савина Ольга Александровна',
    rang: 'Специалист по корпоративной культуре',
    subdivision: 'HR-отдел',
    address: 'savina.oa@mail.ru',
  },
  {
    key: 69,
    name: 'Котов Илья Сергеевич',
    rang: 'Специалист по технической документации',
    subdivision: 'Отдел документации',
    address: 'kotov.is@mail.ru',
  },
  {
    key: 70,
    name: 'Зимина Татьяна Владимировна',
    rang: 'Специалист по кадровому делопроизводству',
    subdivision: 'Отдел кадров',
    address: 'zimina.tv@mail.ru',
  },
  {
    key: 71,
    name: 'Марков Денис Олегович',
    rang: 'Специалист по информационной безопасности',
    subdivision: 'Отдел информационной безопасности',
    address: 'markov.do@mail.ru',
  },
  {
    key: 72,
    name: 'Лапина Ирина Анатольевна',
    rang: 'Специалист по работе с персоналом',
    subdivision: 'HR-отдел',
    address: 'lapina.ia@mail.ru',
  },
  {
    key: 73,
    name: 'Суханов Андрей Викторович',
    rang: 'Специалист по системному администрированию',
    subdivision: 'IT-отдел',
    address: 'sukhanov.av@mail.ru',
  },
  {
    key: 74,
    name: 'Горшкова Наталья Игоревна',
    rang: 'Специалист по кадровому учету',
    subdivision: 'Отдел кадров',
    address: 'gorshkova.ni@mail.ru',
  },
  {
    key: 75,
    name: 'Терехов Павел Сергеевич',
    rang: 'Специалист по технической поддержке пользователей',
    subdivision: 'IT-отдел',
    address: 'terekhov.ps@mail.ru',
  },
  {
    key: 76,
    name: 'Фролова Мария Дмитриевна',
    rang: 'Специалист по подбору персонала',
    subdivision: 'HR-отдел',
    address: 'frolova.md@mail.ru',
  },
  {
    key: 77,
    name: 'Шестаков Алексей Андреевич',
    rang: 'Специалист по интеграции систем',
    subdivision: 'IT-отдел',
    address: 'shestakov.aa@mail.ru',
  },
  {
    key: 78,
    name: 'Яковлева Елена Витальевна',
    rang: 'Специалист по кадровому администрированию',
    subdivision: 'Отдел кадров',
    address: 'yakovleva.ev@mail.ru',
  },
  {
    key: 79,
    name: 'Абрамов Дмитрий Олегович',
    rang: 'Специалист по техническому обучению',
    subdivision: 'Отдел обучения',
    address: 'abramov.do@mail.ru',
  },
  {
    key: 80,
    name: 'Устинова Анна Сергеевна',
    rang: 'Специалист по развитию персонала',
    subdivision: 'HR-отдел',
    address: 'ustinova.as@mail.ru',
  },
  {
    key: 81,
    name: 'Баранов Игорь Владимирович',
    rang: 'Специалист по сетевым технологиям',
    subdivision: 'IT-отдел',
    address: 'baranov.iv@mail.ru',
  },
  {
    key: 82,
    name: 'Воронцова Ольга Александровна',
    rang: 'Специалист по кадровому резерву',
    subdivision: 'HR-отдел',
    address: 'vorontsova.oa@mail.ru',
  },
  {
    key: 83,
    name: 'Гришин Михаил Сергеевич',
    rang: 'Специалист по облачным технологиям',
    subdivision: 'IT-отдел',
    address: 'grishin.ms@mail.ru',
  },
  {
    key: 84,
    name: 'Дорофеева Татьяна Игоревна',
    rang: 'Специалист по оценке персонала',
    subdivision: 'HR-отдел',
    address: 'dorofeeva.ti@mail.ru',
  },
  {
    key: 85,
    name: 'Ермаков Виталий Андреевич',
    rang: 'Специалист по кибербезопасности',
    subdivision: 'Отдел информационной безопасности',
    address: 'ermakov.va@mail.ru',
  },
  {
    key: 86,
    name: 'Жданова Ксения Владимировна',
    rang: 'Специалист по адаптации персонала',
    subdivision: 'HR-отдел',
    address: 'zhdanova.kv@mail.ru',
  },
  {
    key: 87,
    name: 'Зуев Артем Дмитриевич',
    rang: 'Специалист по автоматизации тестирования',
    subdivision: 'Отдел контроля качества',
    address: 'zuev.ad@mail.ru',
  },
  {
    key: 88,
    name: 'Игнатова Екатерина Олеговна',
    rang: 'Специалист по мотивации персонала',
    subdivision: 'HR-отдел',
    address: 'ignatova.eo@mail.ru',
  },
  {
    key: 89,
    name: 'Казаков Роман Сергеевич',
    rang: 'Специалист по технической поддержке 1С',
    subdivision: 'IT-отдел',
    address: 'kazakov.rs@mail.ru',
  },
  {
    key: 90,
    name: 'Лобанова Анастасия Андреевна',
    rang: 'Специалист по кадровому аудиту',
    subdivision: 'HR-отдел',
    address: 'lobanova.aa@mail.ru',
  },
  {
    key: 91,
    name: 'Маслов Денис Викторович',
    rang: 'Специалист по ERP-системам',
    subdivision: 'IT-отдел',
    address: 'maslov.dv@mail.ru',
  },
  {
    key: 92,
    name: 'Носова Ольга Игоревна',
    rang: 'Специалист по кадровому учету',
    subdivision: 'Отдел кадров',
    address: 'nosova.oi@mail.ru',
  },
  {
    key: 93,
    name: 'Овчинников Павел Александрович',
    rang: 'Специалист по технической документации',
    subdivision: 'Отдел документации',
    address: 'ovchinnikov.pa@mail.ru',
  },
  {
    key: 94,
    name: 'Полякова Анна Владимировна',
    rang: 'Специалист по кадровому делопроизводству',
    subdivision: 'Отдел кадров',
    address: 'polyakova.av@mail.ru',
  },
  {
    key: 95,
    name: 'Румянцев Алексей Дмитриевич',
    rang: 'Специалист по технической поддержке',
    subdivision: 'IT-отдел',
    address: 'rumyantsev.ad@mail.ru',
  },
  {
    key: 96,
    name: 'Сазонова Елена Игоревна',
    rang: 'Специалист по кадровому учету',
    subdivision: 'Отдел кадров',
    address: 'sazonova.ei@mail.ru',
  },
  {
    key: 97,
    name: 'Тихомиров Дмитрий Сергеевич',
    rang: 'Специалист по сетевым технологиям',
    subdivision: 'IT-отдел',
    address: 'tikhomirov.ds@mail.ru',
  },
  {
    key: 98,
    name: 'Уварова Марина Александровна',
    rang: 'Специалист по кадровому администрированию',
    subdivision: 'Отдел кадров',
    address: 'uvarova.ma@mail.ru',
  },
  {
    key: 99,
    name: 'Федосеев Иван Андреевич',
    rang: 'Специалист по информационным технологиям',
    subdivision: 'IT-отдел',
    address: 'fedoseev.ia@mail.ru',
  },
  {
    key: 100,
    name: 'Хомякова Ольга Сергеевна',
    rang: 'Специалист по кадровому делопроизводству',
    subdivision: 'Отдел кадров',
    address: 'khomyakova.os@mail.ru',
  },
];

