import React from "react";

interface DataType {
  key: React.Key;
  name: string;
  rang: string;
  subdivision: string;
  address: string;
}

export const usersData: DataType[] = [
  {
    name: 'Laurence Ferry I',
    rang: 'National',
    subdivision: 'Beauty',
    address: 'Nedra.Konopelski0@hotmail.com',
    key: '1',
  },
  {
    name: 'Marion Walker',
    rang: 'District',
    subdivision: 'Grocery',
    address: 'Titus77@hotmail.com',
    key: '2',
  },
  {
    name: 'Edgar Abbott',
    rang: 'Principal',
    subdivision: 'Jewelry',
    address: 'Cleve_Walsh62@hotmail.com',
    key: '3',
  },
  {
    name: 'Julian Beahan MD',
    rang: 'Dynamic',
    subdivision: 'Kids',
    address: 'Eloisa18@yahoo.com',
    key: '4',
  },
  {
    name: "Amber O'Reilly",
    rang: 'Internal',
    subdivision: 'Games',
    address: 'Alayna.Stamm@yahoo.com',
    key: '5',
  },
  {
    name: 'Carroll Boyle',
    rang: 'Regional',
    subdivision: 'Movies',
    address: 'Ludie.Grady20@yahoo.com',
    key: '6',
  },
  {
    name: 'Dwight Ferry',
    rang: 'Corporate',
    subdivision: 'Grocery',
    address: 'Jeffry.Lueilwitz15@gmail.com',
    key: '7',
  },
  {
    name: 'Miss Gretchen Veum',
    rang: 'District',
    subdivision: 'Books',
    address: 'Gino67@hotmail.com',
    key: '8',
  },
  {
    name: 'Josh Bruen-Collins',
    rang: 'International',
    subdivision: 'Clothing',
    address: 'Valentin47@hotmail.com',
    key: '9',
  },
  {
    name: 'Ivan Koss',
    rang: 'District',
    subdivision: 'Outdoors',
    address: 'Reyna61@hotmail.com',
    key: '10',
  },
  {
    name: 'Alison Hansen',
    rang: 'Dynamic',
    subdivision: 'Shoes',
    address: 'Jovani12@hotmail.com',
    key: '11',
  },
  {
    name: 'Ms. Kara Harber-Tremblay',
    rang: 'Human',
    subdivision: 'Beauty',
    address: 'Ethyl36@hotmail.com',
    key: '12',
  },
  {
    name: 'Michele Steuber',
    rang: 'National',
    subdivision: 'Games',
    address: 'Olin76@hotmail.com',
    key: '13',
  },
  {
    name: 'Hannah West',
    rang: 'Customer',
    subdivision: 'Home',
    address: 'Florian_Braun@hotmail.com',
    key: '14',
  },
  {
    name: 'Marvin Marks III',
    rang: 'National',
    subdivision: 'Movies',
    address: 'Catalina_Braun@yahoo.com',
    key: '15',
  },
  {
    name: 'Marianne Gottlieb',
    rang: 'Lead',
    subdivision: 'Jewelry',
    address: 'Dalton.Emmerich@yahoo.com',
    key: '16',
  },
  {
    name: 'Silvia Harris IV',
    rang: 'Principal',
    subdivision: 'Toys',
    address: 'Gabe96@hotmail.com',
    key: '17',
  },
  {
    name: 'Dr. Eugene Pouros',
    rang: 'Legacy',
    subdivision: 'Automotive',
    address: 'Alvis_Hartmann12@hotmail.com',
    key: '18',
  },
  {
    name: 'Roberta Turner',
    rang: 'Direct',
    subdivision: 'Outdoors',
    address: 'Raven_Tremblay18@hotmail.com',
    key: '19',
  },
  {
    name: 'Sam Cremin',
    rang: 'Senior',
    subdivision: 'Beauty',
    address: 'Bryon97@hotmail.com',
    key: '20',
  },
  {
    name: 'Pete Bernier',
    rang: 'Principal',
    subdivision: 'Automotive',
    address: 'Violette.Bergstrom18@yahoo.com',
    key: '21',
  },
  {
    name: 'Melody Wilkinson',
    rang: 'Legacy',
    subdivision: 'Kids',
    address: 'Justice.Jerde-Reinger73@yahoo.com',
    key: '22',
  },
  {
    name: 'Opal Daniel',
    rang: 'Direct',
    subdivision: 'Baby',
    address: 'Clare_Lowe5@hotmail.com',
    key: '23',
  },
  {
    name: 'Mrs. Lana Kautzer',
    rang: 'Corporate',
    subdivision: 'Baby',
    address: 'Thalia.Collier59@yahoo.com',
    key: '24',
  },
  {
    name: 'Craig Schmidt',
    rang: 'Central',
    subdivision: 'Outdoors',
    address: 'Ola.Dooley58@gmail.com',
    key: '25',
  },
  {
    name: 'Danny Abbott',
    rang: 'Regional',
    subdivision: 'Health',
    address: 'Casimer_Klocko@hotmail.com',
    key: '26',
  },
  {
    name: 'Dixie Wuckert',
    rang: 'District',
    subdivision: 'Toys',
    address: 'Amie.Brakus@hotmail.com',
    key: '27',
  },
  {
    name: 'Elvira Ebert IV',
    rang: 'Principal',
    subdivision: 'Electronics',
    address: 'Sylvia.Rosenbaum33@yahoo.com',
    key: '28',
  },
  {
    name: 'Alexandra Stroman',
    rang: 'Customer',
    subdivision: 'Kids',
    address: 'Durward18@gmail.com',
    key: '29',
  },
  {
    name: 'Sonja Hoppe',
    rang: 'Future',
    subdivision: 'Home',
    address: 'Johann.Carter@gmail.com',
    key: '30',
  },
  {
    name: 'Irene Hamill-Fisher',
    rang: 'Human',
    subdivision: 'Outdoors',
    address: 'Stacy_Cormier84@hotmail.com',
    key: '31',
  },
  {
    name: 'Josh Schmitt',
    rang: 'Forward',
    subdivision: 'Jewelry',
    address: 'Wanda_Kub@hotmail.com',
    key: '32',
  },
  {
    name: 'Dr. Annie Christiansen',
    rang: 'Dynamic',
    subdivision: 'Baby',
    address: 'Dorothy.Parisian56@gmail.com',
    key: '33',
  },
  {
    name: 'Cory Daniel',
    rang: 'Forward',
    subdivision: 'Tools',
    address: 'Cordia.Swift@gmail.com',
    key: '34',
  },
  {
    name: 'Mark Grant',
    rang: 'Global',
    subdivision: 'Tools',
    address: 'Quinten_Casper@hotmail.com',
    key: '35',
  },
  {
    name: 'Conrad Wunsch',
    rang: 'Internal',
    subdivision: 'Grocery',
    address: 'Bailey_Carter27@yahoo.com',
    key: '36',
  },
  {
    name: 'Conrad Quitzon',
    rang: 'Forward',
    subdivision: 'Movies',
    address: 'Daphne_Jast@yahoo.com',
    key: '37',
  },
  {
    name: 'Flora Abbott',
    rang: 'Senior',
    subdivision: 'Tools',
    address: 'Octavia.Schamberger73@gmail.com',
    key: '38',
  },
  {
    name: 'Adam McGlynn',
    rang: 'Central',
    subdivision: 'Toys',
    address: 'Monroe60@yahoo.com',
    key: '39',
  },
  {
    name: "Carol O'Keefe",
    rang: 'Human',
    subdivision: 'Clothing',
    address: 'Christ_Gutmann56@hotmail.com',
    key: '40',
  },
  {
    name: 'Tom Crooks I',
    rang: 'National',
    subdivision: 'Tools',
    address: 'Myra92@yahoo.com',
    key: '41',
  },
  {
    name: 'Edmund Rice',
    rang: 'Regional',
    subdivision: 'Home',
    address: 'Jo38@hotmail.com',
    key: '42',
  },
  {
    name: 'Mr. Clark Reichert Jr.',
    rang: 'Product',
    subdivision: 'Books',
    address: 'Lincoln_Hettinger46@gmail.com',
    key: '43',
  },
  {
    name: 'Sonia Hand',
    rang: 'Product',
    subdivision: 'Tools',
    address: 'Dexter69@hotmail.com',
    key: '44',
  },
  {
    name: 'Brad Torp',
    rang: 'Central',
    subdivision: 'Electronics',
    address: 'Guillermo63@yahoo.com',
    key: '45',
  },
  {
    name: 'Steve Walter',
    rang: 'Principal',
    subdivision: 'Shoes',
    address: 'Angela85@yahoo.com',
    key: '46',
  },
  {
    name: 'Eula Veum',
    rang: 'Dynamic',
    subdivision: 'Sports',
    address: 'Sabryna99@hotmail.com',
    key: '47',
  },
  {
    name: 'Woodrow Koepp',
    rang: 'Senior',
    subdivision: 'Beauty',
    address: 'Cydney64@gmail.com',
    key: '48',
  },
  {
    name: 'Dominic Stracke',
    rang: 'Principal',
    subdivision: 'Health',
    address: 'Rubye61@hotmail.com',
    key: '49',
  },
  {
    name: 'Devin Paucek I',
    rang: 'International',
    subdivision: 'Music',
    address: 'Hildegard_Glover@gmail.com',
    key: '50',
  },
];
